name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "needs triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  id: description
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: false
- type: textarea
  id: steps
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: false
- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: dropdown
  id: version
  attributes:
    label: Version
    description: Which version of Project Flow was used?
    options:
      - Current (v0.2.2)
      - Previous (v0.1.11)
      - Older, than v0.1.11
  validations:
    required: true
- type: dropdown
  id: project
  attributes:
    label: Project Template
    description: If this is about `proj-flow init`, which project is used?
    options:
      - cxx
      - Other
  validations:
    required: true
- type: dropdown
  id: os
  attributes:
    label: Operating Systems
    description: Which operating systems have you used? You may select more than one.
    options:
      - macOS
      - Windows
      - Linux
  validations:
    required: false
- type: textarea
  id: context
  attributes:
    label: Init context
    description: If this is about `proj-flow init`, please consider using `--ctx` and uploading the resulting `.context.yaml` here.
  validations:
    required: false
- type: textarea
  id: additional
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      If you selected "Newer" to Game Version, "Other" to Launcher or "Older" for Mod Version, specify here, which was it.
      Please be aware, however, that bugs should be reproduced on latest mod version to provide a high-quality bug description.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
