name: Feature request
description: Suggest an idea for this project
labels: needs triage
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: Provide a clear and concise description of what the problem is.
      placeholder: I'm always frustrated when
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alt
    attributes:
      label: Describe alternatives you've considered
      description: Provide a clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
