name: Build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

env:
  RELEASE: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main' }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      RELEASE: ${{env.RELEASE && fromJson(steps.release.outputs.released)}}
      REFERENCE: ${{steps.release.outputs.tag}}

    steps:
      - name: Print-a-lot
        run: |
          echo ${{toJson(env.RELEASE)}}
          echo ${{toJson(github)}}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Draft a release
        id: release
        if: ${{ fromJson(env.RELEASE) }}
        run: python ./.flow/flow.py github release

  M:
    name: Select builds
    runs-on: ubuntu-latest
    needs: release
    outputs:
      RELEASE: ${{needs.release.outputs.RELEASE}}
      REFERENCE: ${{needs.release.outputs.REFERENCE}}
      matrix: ${{steps.flow.outputs.matrix}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find builds
        id: flow
        run: python ./.flow/flow.py github matrix

      - name: Print-a-lot
        run: |
          echo ${{toJson(needs.release.outputs.RELEASE)}}
          echo ${{toJson(needs.release.outputs.REFERENCE)}}
